### PR TITLE
Prepare to upload version 3 on PyPI (pypi.org)

### PR DESCRIPTION
**Pull request by fedelibre**
Set the minimum version requirements for Python and python-ly.
Fix Classifier name as per https://pypi.org/classifiers/

### CODE REVIEW

**Comment by fedelibre** [comment]
I just read the minimum python3 version in the Changelog file.

I've uploaded it on Test PYPI:
https://test.pypi.org/project/frescobaldi/

`pip install` works fine in Linux only if run normally. It won't work on a virtualenv.
It won't work in Windows (and probably Mac neither, but I didn't test).
The reason is that python-poppler-qt5 is uploaded to PyPI as a pure wheel and needs to be built on each architecture. The build works fine in Linux.
I started working on this two weeks ago and found some solutions to build binary wheels. Then I did not have any time to go on, as my regular job has been very stressful in the last weeks.
So I decided to send this PR and start a discussion about this stuff.
I'll send more details about this matter in the coming days as soon as I have some spare time.

For now you can test it using:

```
pip3 install --user --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple Frescobaldi
```
This should work on Linux.

The best would be doing this installation in a dedicated virtualenv so you can isolate the dependencies and check them:

```
$ pip3 freeze
PyQt5==5.11.3
PyQt5-sip==4.19.13
sip==4.19.8
```

The problem is building python-poppler-qt5 in a virtualenv:

```
$ pip3 install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple Frescobaldi
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting Frescobaldi
  Using cached https://test-files.pythonhosted.org/packages/c1/14/1d665aa4d7a3e3def579960eae41def33d3cc7339de28bc6a03aad2b0b57/frescobaldi-3.0.1b0-py3-none-any.whl
Collecting python-ly>=0.9.4 (from Frescobaldi)
Collecting python-poppler-qt5 (from Frescobaldi)
  Using cached https://files.pythonhosted.org/packages/af/e7/aa451d4ca0910472c4442d8aa6ef44300852926d85ad033b029a22157027/python-poppler-qt5-0.24.2.tar.gz
Building wheels for collected packages: python-poppler-qt5
  Running setup.py bdist_wheel for python-poppler-qt5 ... error
  Complete output from command /home/fede/.virtualenvs/frescobaldi/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lqrtzx5j/python-poppler-qt5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-43bgxk_i --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'popplerqt5' extension
  /usr/bin/python3-sip -I /usr/share/python3-sip -t POPPLER_V0_28_0 -c build/temp.linux-x86_64-3.6 -b build/temp.linux-x86_64-3.6/poppler-qt5.sbf -I /usr/share/python3-sip/PyQt5 -n PyQt5.sip -t WS_X11 -t Qt_5_11_2 poppler-qt5.sip
  sip: Usage: sip [-h] [-V] [-a file] [-b file] [-B tag] [-c dir] [-d file] [-D] [-e] [-f] [-g] [-I dir] [-j #] [-k] [-m file] [-o] [-p module] [-P] [-r] [-s suffix] [-t tag] [-w] [-x feature] [-X id:file] [-y file] [-z file] [@file] [file]
  error: command '/usr/bin/python3-sip' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-poppler-qt5
  Running setup.py clean for python-poppler-qt5
Failed to build python-poppler-qt5
Installing collected packages: python-ly, python-poppler-qt5, Frescobaldi
  Running setup.py install for python-poppler-qt5 ... error
    Complete output from command /home/fede/.virtualenvs/frescobaldi/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lqrtzx5j/python-poppler-qt5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v1jl35s5/install-record.txt --single-version-externally-managed --compile --install-headers /home/fede/.virtualenvs/frescobaldi/include/site/python3.6/python-poppler-qt5:
    running install
    running build
    running build_ext
    building 'popplerqt5' extension
    /usr/bin/python3-sip -I /usr/share/python3-sip -t POPPLER_V0_28_0 -c build/temp.linux-x86_64-3.6 -b build/temp.linux-x86_64-3.6/poppler-qt5.sbf -I /usr/share/python3-sip/PyQt5 -n PyQt5.sip -t WS_X11 -t Qt_5_11_2 poppler-qt5.sip
    sip: Usage: sip [-h] [-V] [-a file] [-b file] [-B tag] [-c dir] [-d file] [-D] [-e] [-f] [-g] [-I dir] [-j #] [-k] [-m file] [-o] [-p module] [-P] [-r] [-s suffix] [-t tag] [-w] [-x feature] [-X id:file] [-y file] [-z file] [@file] [file]
    error: command '/usr/bin/python3-sip' failed with exit status 1
    
    ----------------------------------------
Command "/home/fede/.virtualenvs/frescobaldi/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lqrtzx5j/python-poppler-qt5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v1jl35s5/install-record.txt --single-version-externally-managed --compile --install-headers /home/fede/.virtualenvs/frescobaldi/include/site/python3.6/python-poppler-qt5" failed with error code 1 in /tmp/pip-install-lqrtzx5j/python-poppler-qt5/
```

**Comment by fedelibre** [comment]
@uliska This PR needs an update of python version to 3.3. For some reason I have a problem with my local branch and I cannot push a new commit. So I would leave this to you once you think it can be merged.

**Comment by uliska** [comment]
Do you mean you have something in your PR that requires 3.3?
Then you should be happy that I had already raised the requirement to 3.3 in c62d65aafab2f958083bc8f4c57473744e68b061#diff-f4bdfabe2e489d538913ef26e51071df

Before I try testing the PR (I'm not sure if I'll be able to properly do so, given that I *have* a working installation already ...) could you please clarify if I correctly understood your comment, @fedelibre ?

**Comment by fedelibre** [comment]
No, my PR did not change. I want to raise the requirement in this PR just because I'm aware of your change.

You can test the pip install in a virtualenv, but there are a few issues related to python-poppler-qt5 and also the pip frescobaldi executable. I started again my work on this yesterday and I'm taking some notes. I think I'll put them in the wiki eventually and open a new issue to discuss them.

**Comment by uliska** [comment]
OK, I see. I applied the change (and I think you could have done so the same way I did, through the web interface ;-) ).

I'm afraid I won't be of much help testing this.

**Comment by fedelibre** [comment]
@wbsoft I'm closing this as I think it doesn't add much... I mean, I've noticed that the python-ly version is already set in [appinfo.py](https://github.com/frescobaldi/frescobaldi/blob/master/frescobaldi_app/appinfo.py#L40). The Ukrainian spelling issue can be fixed later when/if you want to update the version on the PyPI.

**Pull request closed without merging**
