### PR TITLE
Update the installation instructions after Qt6 port

### PR DESCRIPTION
**Pull request by fedelibre**
@bmjcode While testing the installation instructions in a 24.04 LTS Ubuntu container,  I noticed that qpageview won't let Frescobaldi launch because Qt 6.4 is missing a QtPdf module:

```
⬢ [fede@toolbx frescobaldi]$ PYTHONPATH=../qpageview ./frescobaldi
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.2
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name frescobaldi 
  *  browser-subprocess-path /usr/lib/qt6/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

Gtk-Message: 23:39:43.139: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/mainwindow.py", line 1124, in slotRecentFilesAction
    d = self.openUrl(action.url)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/mainwindow.py", line 439, in openUrl
    for d in self.openUrls([url], encoding, ignore_errors):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/mainwindow.py", line 463, in openUrls
    doc = app.openUrl(url, encoding)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/app.py", line 103, in openUrl
    d.load(url)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/document.py", line 268, in load
    self.loaded()
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/documents.py", line 96, in update
    doc = pagedview.loadPdf(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/pagedview.py", line 312, in loadPdf
    return qpageview.loadPdf(filename, getRenderer("pdf"))
                                       ^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/pagedview.py", line 293, in getRenderer
    import qpageview.pdf
  File "/var/home/fede/src/frescobaldi/qpageview/qpageview/pdf.py", line 34, in <module>
    from PyQt6.QtPdf import QPdfDocument, QPdfDocumentRenderOptions, QPdfLinkModel
ImportError: cannot import name 'QPdfLinkModel' from 'PyQt6.QtPdf' (/usr/lib/python3/dist-packages/PyQt6/QtPdf.abi3.so)
Traceback (most recent call last):
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/job/__init__.py", line 341, in _finished
    self._bye(success)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/job/__init__.py", line 358, in _bye
    self.done(success)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/job/manager.py", line 67, in _finished
    app.jobFinished(self.document(), self._job, success)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/signals.py", line 317, in call
    return self.func(*args[self.argslice], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/documents.py", line 41, in _on_job_finished
    if group(document).update():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/documents.py", line 96, in update
    doc = pagedview.loadPdf(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/pagedview.py", line 312, in loadPdf
    return qpageview.loadPdf(filename, getRenderer("pdf"))
                                       ^^^^^^^^^^^^^^^^^^
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/pagedview.py", line 293, in getRenderer
    import qpageview.pdf
  File "/var/home/fede/src/frescobaldi/qpageview/qpageview/pdf.py", line 34, in <module>
    from PyQt6.QtPdf import QPdfDocument, QPdfDocumentRenderOptions, QPdfLinkModel
ImportError: cannot import name 'QPdfLinkModel' from 'PyQt6.QtPdf' (/usr/lib/python3/dist-packages/PyQt6/QtPdf.abi3.so)
Unable to detect a web browser to launch 'https://github.com/frescobaldi/frescobaldi/issues/new?title=ImportError: cannot import name 'QPdfLinkModel' from 'PyQt6.QtPdf' (/usr/lib/python3/dist-packages/PyQt6/QtPdf.abi3.so)%0A&body=Traceback (most recent call last):%0A  File %22/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/documents.py%22, line 41, in _on_job_finished%0A    if group(document).update():%0A       %5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A  File %22/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/documents.py%22, line 96, in update%0A    doc %3D pagedview.loadPdf(filename)%0A          %5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A  File %22/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/pagedview.py%22, line 312, in loadPdf%0A    return qpageview.loadPdf(filename, getRenderer(%22pdf%22))%0A                                       %5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A  File %22/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/pagedview.py%22, line 293, in getRenderer%0A    import qpageview.pdf%0A  File %22/var/home/fede/src/frescobaldi/qpageview/qpageview/pdf.py%22, line 34, in %3Cmodule%3E%0A    from PyQt6.QtPdf import QPdfDocument, QPdfDocumentRenderOptions, QPdfLinkModel%0AImportError: cannot import name 'QPdfLinkModel' from 'PyQt6.QtPdf' (/usr/lib/python3/dist-packages/PyQt6/QtPdf.abi3.so)%0A%0AOptionally describe below what you were doing:%0A%0AFrescobaldi: 3.3.0%0AExtension API: 0.9.0%0APython: 3.12.3%0AGit branch: install-qt6%0Aon commit: 5d419c83%0Apython-ly: 0.9.7%0AQt: 6.4.2%0APyQt: 6.6.1%0Aqpageview: 0.6.2%0AOS: Linux-6.11.8-300.fc41.x86_64-x86_64-with-glibc2.39 (Ubuntu 24.04.1 LTS)%0AInstallation kind: distro package or installed from source'
```

I guess that we'd better set a minimum version for pyqt6 in Frescobaldi pyproject.toml file?

### CODE REVIEW

**Comment by bmjcode** [comment]
> I guess that we'd better set a minimum version for pyqt6 in Frescobaldi pyproject.toml file?

Yes, we need at least Qt 6.6 for PDF support.

**Comment by fedelibre** [comment]
> Yes, we need at least Qt 6.6 for PDF support.

I would add the minimum version in a separate PR. My plan is:

1. Make new releases for python-ly and qpageview
2. Dump Frescobaldi version and update dependencies minimum versions in pyproject.toml

**Comment by bmjcode** [comment]
Sounds good. To clarify, we're not doing the Frescobaldi release yet, just the dependencies?

**Comment by fedelibre** [comment]
I don't know what it may be the reason, but I guess there's a problem in your installation.

Please check that your qpageview git directory is up-to-date (`git pull origin master`) and review the INSTALL.md file from the beginning.

**Comment by ksnortum** [comment]
My qpageview was not up to date.  All is good now.  Sorry for the noise.

**Comment by ksnortum** [comment]
Again, this may be my setup, but the 6.6.1 version of python3-pyqt6.qtpdf on Ubuntu 24.04 seems to be missing QPdfLinkModel:

	$ python3
	Python 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> from PyQt6.QtPdf import QPdfDocument, QPdfDocumentRenderOptions, QPdfLinkModel
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	ImportError: cannot import name 'QPdfLinkModel' from 'PyQt6.QtPdf' (/usr/lib/python3/dist-packages/PyQt6/QtPdf.abi3.so)

**Comment by fedelibre** [comment]
Yes, I can reproduce it on my Ubuntu 24.04 container. Here's the error displayed by Frescobaldi when I engrave a file:

```
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/pagedview.py", line 293, in getRenderer
    import qpageview.pdf
  File "/var/home/fede/src/frescobaldi/qpageview/qpageview/pdf.py", line 34, in <module>
    from PyQt6.QtPdf import QPdfDocument, QPdfDocumentRenderOptions, QPdfLinkModel
ImportError: cannot import name 'QPdfLinkModel' from 'PyQt6.QtPdf' (/usr/lib/python3/dist-packages/PyQt6/QtPdf.abi3.so)
```

And these are the versions retrieved by Frescobaldi:

> Qt: 6.4.2
> PyQt: 6.6.1

According to [Qt6 docs](https://doc.qt.io/qt-6/qpdflinkmodel.html) QPdfLinkModel was introduced in 6.6 series, but it's not specified which minor version.
@bmjcode The error is caused by Qt=6.4.2? I mean, maybe Ubuntu should upgrade the Qt version to almost match the PyQt version?

I've just installed an Ubuntu 24.10 container and it runs just fine with the following dependencies:

> Qt: 6.6.2
> PyQt: 6.7.1

**Comment by bmjcode** [comment]
> According to [Qt6 docs](https://doc.qt.io/qt-6/qpdflinkmodel.html) QPdfLinkModel was introduced in 6.6 series, but it's not specified which minor version. @bmjcode The error is caused by Qt=6.4.2?

Correct.

> I mean, maybe Ubuntu should upgrade the Qt version to almost match the PyQt version?

I'm sure Ubuntu has their reasons for sticking to 6.4.2. What those reasons *are* is beyond me, though.

**Comment by ksnortum** [comment]
I just tried to install Frescobaldi on a brand-new Ubuntu 24.04 docker container and I got this error with the first `pipx` command:

    # pipx install --system-site-packages --editable ./frescobaldi
    Fatal error from pip prevented installation. Full pip output in file:
        /root/.local/state/pipx/log/cmd_2024-12-04_14.54.57_pip_errors.log

    pip seemed to fail to build package:
        qpageview

    Some possibly relevant errors from pip install:
        error: subprocess-exited-with-error
        ModuleNotFoundError: No module named 'PyQt5'

    Error installing frescobaldi from spec '/home/ubuntu/git-repos/frescobaldi'.

I've attached the error log.
[pip-error-log.txt](https://github.com/user-attachments/files/18015422/pip-error-log.txt)

**Comment by bmjcode** [comment]
We're still finishing up the qpageview release, so the one on `pip` is still the PyQt5 version.

**Comment by fedelibre** [comment]
It's an easy PR, I'll merge it

**Pull request merged**
