### PR TITLE
Release Frescobaldi 3.3.0

### PR DESCRIPTION
**Pull request by fedelibre**
I set 21st of March as a target release date. We thought that 3.3.0 would have come out last Christmas and instead we had to wait for Spring! :-)

Please check if I missed anything.
I didn't dare to update the `credits.md` file, but I'm sure that Jean should be put there. @jeanas feel free to add yourself there and describe what you did; you can add a commit on top of mine.

I've added @19joho66 who usually makes the Windows package.

### CODE REVIEW

**Comment by dliessi** [comment]
I tried building the Mac app (on a relatively old Intel machine) and I have some difficulties in making convert-ly and the other Python scripts work. I'll try sorting it out before the deadline.

My Intel build should work on more recent Intel systems. I expect it to work also on Apple Silicon systems with Rosetta 2 (automatic x86-64 to ARM translator) but I haven't tried. However, I found a volunteer for building natively on Apple Silicon, although we haven't setup his machine yet as I'm waiting for some updates to make their way into MacPorts. If we succeed, I'll add his name to credits.md.

Speaking of which, I think @19joho66 is not in credits.md.

**Review by PeterBjuhr — APPROVED** [review]

**Comment by fedelibre** [comment]
> Speaking of which, I think @19joho66 is not in credits.md.

There's also another new contributor: @mr-bronson

**Comment by 19joho66** [comment]
Hi, my name is Jörg Hoffmann

**Comment by fedelibre** [comment]
Jean, I think you can just add `@mr-bronson` for the moment. I would like to merge this within tomorrow so we can make the release on 21st.

Thanks

**Comment by fedelibre** [comment]
Jean, I've squashed your commits into one and changed the release date to 26th of March (as discussed in another issue).
I would merge this PR tomorrow. Let's see what else will get merged until Sunday.

I think the usual process is making the new release on Github, then Windows and Mac packagers will add the installers. I hope @dliessi and @19joho66 can try building the installers asap, so we can be confident it will work before creating the git tag.

**Comment by fedelibre** [comment]
@19joho66 Just to be sure you did not miss it, we did not announce it yet but we made the [3.3.0 release](https://github.com/frescobaldi/frescobaldi/releases/tag/v3.3.0). You can proceed with building the Windows binary when you have time. Thanks

**Pull request merged**
